download_dir: tf_data
bg_path: tf_data/bg_noise
background_volume: 0.1
background_frequency: 0.8
silence_percentage: 10.0
unknown_percentage: 10.0
time_shift_ms: 100.0
sample_rate: 16000
clip_duration_ms: 1000
window_size_ms: 30.0
window_stride_ms: 20.0
feature_type: mfcc
dct_coefficient_count: 10
epochs: 36
num_train_samples: -1
num_val_samples: -1
num_test_samples: -1
batch_size: 100
num_bin_files: 1000
bin_file_path: tf_data/kws_test_files
model_architecture: ds_cnn
run_test_set: True
saved_model_path: trained_models/kws_model.h5
model_init_path: None
tfl_file_name: ../models/kws_ref_model.tflite
learning_rate: 1e-05
lr_sched_name: step_function
plot_dir: ./plots
target_set: test